x = 3;
x = 3 + 2;
x = 3 * 2;
x = 3 ** 2;
x = 5;
while(x>2){
	x = x - 1;
}

print x;
println ;

y = 10;
y = y % x;
y = y / x ;

z = 20;
z = z - 10;
z = z * 1.05;

s = "Hello world";
print s;

a1 = [1,2,3];
a2 = ["1",2,2.5];
print a1[1];

x = 10;
while (true){
	x = x - 2;
	if (x <= 0) {
		break;
	}
	else{
		print x;
	}
}

for(i in range(10)){
	print i;
}